# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [2]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [ ]:
# Write your code here:
a=np.version.version
print(a)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [ ]:
# Write your code here:
array=np.array([0,1,2,3,4,5,6,7,8,9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [ ]:
# Write your code here:
array=np.ones((3,3),dtype=bool)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
odd=arr[arr%2==1]
odd

array([1, 3, 5, 7, 9])

### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
arr=np.where(arr%2==1,-1,arr)
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
replace_odd=np.where(arr%2==1,-1,arr)
print(replace_odd)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [ ]:
# Input — do not modify
arr = np.arange(10)

In [ ]:
# Write your code here:
reshaped_arr = arr.reshape(2, -1)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here
print(a,b,sep="\n")
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [ ]:
# Input — do not modify
a = np.array([1, 2, 3])

In [ ]:
# Write your code here:
a=np.r_[np.repeat(a,3),np.tile(a,3)]
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
common=np.intersect1d(a,b)
common

array([2, 4])

### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [ ]:
# Write your code here:
rem=np.setdiff1d(a,b)
rem

array([1, 2, 3, 4])

### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
pos=np.where(a==b)
pos

(array([1, 3, 5, 7]),)

### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [ ]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
# Write your code here:
item=a[np.where((a>=5) & (a<=10))]
item

array([ 6,  9, 10])

### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [ ]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [ ]:
# Write your code here:
vectorized_maxx = np.vectorize(maxx)
result = vectorized_maxx(a, b)
print(result)

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
print(arr)
npswap=arr[:,[1,0,2]]
print(npswap)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
print(arr)
npswap=arr[[1,0,2],:]
print(npswap)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
print(arr)
rev=arr[::-1,:]
print(rev)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
print(arr)
rev_c=arr[:,::-1]
print(rev_c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [ ]:
# Write your code here:
rand_arr=np.random.uniform(5,10,size=(5,3))
rand_arr

array([[9.89311892, 9.05841575, 5.85970506],
       [9.08112374, 6.37036874, 7.15852092],
       [9.7001491 , 9.08824689, 6.68055975],
       [5.87705227, 6.86416023, 5.02844254],
       [6.26213177, 8.97831254, 5.07627486]])

### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [ ]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [ ]:
# Write your code here:
print(rand_arr)
rand_new=np.round(rand_arr,3)
rand_new

[[0.37625245 0.5928054  0.62994188]
 [0.14260031 0.9338413  0.94637988]
 [0.60229666 0.38776628 0.363188  ]
 [0.20434528 0.27676506 0.24653588]
 [0.173608   0.96660969 0.9570126 ]]


array([[0.376, 0.593, 0.63 ],
       [0.143, 0.934, 0.946],
       [0.602, 0.388, 0.363],
       [0.204, 0.277, 0.247],
       [0.174, 0.967, 0.957]])

### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [ ]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [ ]:
# Write your code here:
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [ ]:
# Input — do not modify
a = np.arange(15)

In [ ]:
# Write your code here:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [ ]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [ ]:
# Write your code here:
np.set_printoptions(threshold=np.inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [7]:
# Write your code here:
np.set_printoptions(suppress=True)
url='https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='utf-8')
iris_1d

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iri

### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [9]:
# Write your code here:
text_col=iris_1d['f4']
print(text_col)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [37]:
# Write your code here:
iris_2d = np.array([list(row)[:4] for row in iris_1d])
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [11]:
# Write your code here:
sepal_length = iris_2d[:, 0]
mean_val = np.mean(sepal_length)
median_val = np.median(sepal_length)
std_val = np.std(sepal_length)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)

Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [12]:
# Write your code here:
s_min = sepal_length.min()
s_max = sepal_length.max()
normalized_sepal_length = (sepal_length - s_min) / (s_max - s_min)
print(normalized_sepal_length)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [14]:
# Write your code here:
exp_values = np.exp(sepal_length)
softmax_scores = exp_values / np.sum(exp_values)
print(softmax_scores)
print(np.sum(softmax_scores))

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [17]:
# Write your code here:
sepal_length = iris_2d[:, 0]
boundaries = np.percentile(sepal_length, [5, 95])
print(f"5th Percentile:  {boundaries[0]:.3f}")
print(f"95th Percentile: {boundaries[1]:.3f}")

5th Percentile:  4.600
95th Percentile: 7.255


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [19]:
# Write your code here:
iris_2dc=iris_2d.copy()
random_spots = np.random.choice(iris_2dc.size, 20, replace=False)
row_indices, col_indices = np.unravel_index(random_spots, iris_2dc.shape)
iris_2dc[row_indices, col_indices] = np.nan
total_missing = np.isnan(iris_2dc).sum()
print(f"Total missing values inserted: {total_missing}")

Total missing values inserted: 20


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [22]:
# Write your code here:
sepal_length = iris_2dc[:, 0]
is_missing = np.isnan(sepal_length)
missing_count = np.sum(is_missing)
missing_positions = np.where(is_missing)[0]
print(f"Number of missing values: {missing_count}")
print(f"Positions of missing values: {missing_positions}")

Number of missing values: 4
Positions of missing values: [ 60 108 116 129]


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [29]:
# Write your code here:
condition_1 = iris_2dc[:, 2] > 1.5  # Petal length > 1.5
condition_2 = iris_2dc[:, 0] < 5.0  # Sepal length < 5.0
filtered_rows = iris_2dc[condition_1 & condition_2]
print(filtered_rows)

[[4.8 3.4 1.6 nan]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [24]:
# Write your code here:
has_nan = np.isnan(iris_2dc).any(axis=1)
clean_iris = iris_2dc[~has_nan]
print(f"Original number of rows: {iris_2d.shape[0]}")
print(f"Number of rows after dropping NaNs: {clean_iris.shape[0]}")

Original number of rows: 150
Number of rows after dropping NaNs: 131


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [26]:
# Write your code here:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]
correlation = np.corrcoef(sepal_length, petal_length)[0,1]
print(f"Correlation between sepal length and petal length: {correlation}")

Correlation between sepal length and petal length: 0.8717541573048718


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [27]:
# Write your code here:
has_missing = np.isnan(iris_2dc).any()
total_missing = np.isnan(iris_2dc).sum()
print(f"Total number of missing values: {total_missing}")

Total number of missing values: 20


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [31]:
# Write your code here:
iris_clean = np.nan_to_num(iris_2dc, nan=0.0)
print("Total missing values after replacement:", np.isnan(iris_clean).sum())
print(iris_clean)

Total missing values after replacement: 0
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0. ]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0. ]
 [4.8 3.  1.4 0. ]
 [4.3 0.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 0.  0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0. ]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.

### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [32]:
# Write your code here:
species_column = iris_1d['f4']
unique_species, counts = np.unique(species_column, return_counts=True)
print("Unique Species:", unique_species)
print("Their Counts:  ", counts)

Unique Species: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
Their Counts:   [50 50 50]


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [42]:
# Write your code here:
petal_length = iris_2d[:, 2]
bin_edges = [3, 5]
bin_indexes = np.digitize(petal_length, bins=bin_edges)
label_map = np.array(['small', 'medium', 'large'])
petal_categories = label_map[bin_indexes]
print(petal_categories)

#new 2d matrix with replaced 3rd column
iris_mixed = iris_2d.astype('object')
iris_mixed[:, 2] = petal_categories
print(iris_mixed)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'large' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'large' 'large' 'large' 'large' '

### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [43]:
# Write your code here:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]
volume = (np.pi * petal_length * (sepal_length ** 2)) / 3
iris_3d = np.column_stack((iris_2d, volume))
print(iris_3d)

[[  5.1          3.5          1.4          0.2         38.13265163]
 [  4.9          3.           1.4          0.2         35.20049849]
 [  4.7          3.2          1.3          0.2         30.07237208]
 [  4.6          3.1          1.5          0.2         33.23805027]
 [  5.           3.6          1.4          0.2         36.65191429]
 [  5.4          3.9          1.7          0.4         51.91167701]
 [  4.6          3.4          1.4          0.3         31.02218026]
 [  5.           3.4          1.5          0.2         39.26990817]
 [  4.4          2.9          1.4          0.2         28.38324243]
 [  4.9          3.1          1.5          0.1         37.71481981]
 [  5.4          3.7          1.5          0.2         45.80442089]
 [  4.8          3.4          1.6          0.2         38.60389053]
 [  4.8          3.           1.4          0.1         33.77840421]
 [  4.3          3.           1.1          0.1         21.29895099]
 [  5.8          4.           1.2          0.2  

### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [44]:
# Write your code here:
species_column = iris_1d['f4']
unique_species = np.unique(species_column)
probabilities = [0.50, 0.25, 0.25]
rigged_sample = np.random.choice(unique_species, size=150, p=probabilities, replace=True)
sampled_species, counts = np.unique(rigged_sample, return_counts=True)
print("Rigged Sample Distribution:")
for name, count in zip(sampled_species, counts):
    print(f"{name}: {count}")

Rigged Sample Distribution:
Iris-setosa: 69
Iris-versicolor: 42
Iris-virginica: 39


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [45]:
# Write your code here:
is_setosa = iris_1d['f4'] == 'Iris-setosa'
setosa_flowers = iris_1d[is_setosa]
setosa_petal_lengths = setosa_flowers['f2']
unique_lengths = np.unique(setosa_petal_lengths)
second_longest = unique_lengths[-2]
print(f"All unique setosa petal lengths (sorted): \n{unique_lengths}\n")
print(f"The second longest petal length is: {second_longest}")

All unique setosa petal lengths (sorted): 
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.9]

The second longest petal length is: 1.7


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [46]:
# Write your code here:
sort_indexes = np.argsort(iris_2d[:, 0])
print(iris_2d[sort_indexes])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.5 4.5 1.7]
 [5.  3.5 1.3 0.3]
 [5.  3.3 1.4 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.2 1.2 0.2]
 [5.  3.  1.6 0.2]
 [5.  2.3 3.3 1. ]
 [5.  3.5 1.6 0.6]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 2.5 3.  1.1]
 [5.2 3.5 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [5.2 3.4 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.  4.5 1.5]
 [5.4 3.7 1.5 0.2]
 [5.4 3.4 1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 4.2 1.

### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [47]:
# Write your code here:
petal_length = iris_2d[:, 2]
unique_vals, counts = np.unique(petal_length, return_counts=True)
highest_count_index = np.argmax(counts)
most_frequent = unique_vals[highest_count_index]
print(f"The most frequent petal length is: {most_frequent} cm")
print(f"It appears {counts[highest_count_index]} times in the dataset!")

The most frequent petal length is: 1.5 cm
It appears 14 times in the dataset!


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [48]:
# Write your code here:
petal_width = iris_2d[:, 3]
is_greater = petal_width > 1.0
first_position = np.argmax(is_greater)
print(f"The first occurrence is at row index: {first_position}")
print(f"The actual value at that position is: {petal_width[first_position]} cm")

The first occurrence is at row index: 50
The actual value at that position is: 1.4 cm


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [50]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [51]:
# Write your code here:
clipped_a = np.clip(a, a_min=10, a_max=30)
print("Original array:", a)
print("Clipped array: ", clipped_a)

Original array: [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Clipped array:  [27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [52]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [53]:
# Write your code here:
sorted_indexes = np.argsort(a)
top_5_positions = sorted_indexes[-5:][::-1]
print("Original array:", a)
print("Top 5 positions:", top_5_positions)

Original array: [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Top 5 positions: [15 10  3  7 18]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [56]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [57]:
# Write your code here:
row_counts = [np.unique(row, return_counts=True) for row in arr]
print("Original Array:")
print(arr)

print("\nRow-wise Counts:")
for i, (vals, counts) in enumerate(row_counts):
    print(f"Row {i}:")
    print(f"  Values: {vals}")
    print(f"  Counts: {counts}")

Original Array:
[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]

Row-wise Counts:
Row 0:
  Values: [1 3 4 5 6 8 9]
  Counts: [1 2 1 1 1 2 2]
Row 1:
  Values: [ 1  2  3  5  7  9 10]
  Counts: [2 1 3 1 1 1 1]
Row 2:
  Values: [2 4 5 6 8]
  Counts: [3 2 3 1 1]
Row 3:
  Values: [ 1  3  4  6  8  9 10]
  Counts: [1 2 1 1 2 1 2]
Row 4:
  Values: [1 2 3 6 7 8 9]
  Counts: [2 2 2 1 1 1 1]
Row 5:
  Values: [ 1  2  3  4  5  6  9 10]
  Counts: [1 1 1 1 1 2 2 1]


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [61]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [64]:
# Write your code here:
print(arr_2d)
flattened_arr = np.concatenate(arr_2d)
print(flattened_arr)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.